version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links:
      - app
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - C:\Users\haide\code\Fullstack-Docker\backend\database\db
    ports:
      - "27017:27017"